### ISSUE TITLE
Account Management Example

### ISSUE THREAD

**Issue by scarwm03** [fbsamples/workplace-platform-samples#37] opened 2018-10-31 20:51 UTC
Hi!

I need update the users information in workplace, 
I'm using the account management example, but when i update the user's information, 
the department section is not updated.

Can you help me?

**Comment by eduardogomes** [comment] 2018-11-07 21:02
I was not able to reproduce this behavior, do you mind sharing anonymised version of your file and the command you are executing?

**Comment by eduardogomes** [comment] 2018-11-22 18:41
@scarwm03 Just checking in. Do you mind sharing anonymised version of your file and the command you are executing? If we do not hear back from you I will proceed and close this issue

**Comment by eduardogomes** [comment] 2018-11-27 15:59
Closing out this issue, please get in touch if necessary

**Closed by eduardogomes** 2018-11-27 15:59 UTC
